### ISSUE TITLE
dnslib - build dependency

### ISSUE THREAD

**Issue by ja-pa** [dmachard/dnstap-receiver#1]
Hi,
I'm trying to create OpenWrt package for dnstap-receiver but there seems to be an issue with build dependencies because it fails on error

`ModuleNotFoundError: No module named 'dnslib'`

I don't think that dnslib is real build dependency, the problem is here https://github.com/dmachard/dnstap-receiver/blob/master/setup.py#L4

I think that the easiest fix is to write a version to setup.py and don't import it.

**Comment by dmachard** [comment]
Hi,

This "dnslib" library is required because it's used here https://github.com/dmachard/dnstap-receiver/blob/master/dnstap_receiver/receiver.py#L73

That is why this library is marked as required on the setup.py (line 32)

Denis

**Comment by ja-pa** [comment]
I agree that it's necessary for running dnstap-reciever on the target system, but some build systems (like OpenWrt) create packages on the host system by running setup.py.

If you add dnslib in install_requires, it's ok and most build systems will recognize that it's a dependency for the target system, but if you import some part of your project in setup.py like this  https://github.com/dmachard/dnstap-receiver/blob/master/setup.py#L32 than dnslib became build dependency for host system, which is not necessary, since it's not really needed to run setup.py 

The main point is that host system (which creates package by setup.py)  could be different from target system (which runs application)

Anyway thanks for package  :-)

**Comment by ja-pa** [comment]
I’m not a python expert but I think that PEP517 is related to this issue https://www.python.org/dev/peps/pep-0517/

**Comment by dmachard** [comment]
Issue fixed, I no longer import the project in the installation file

many thanks for your feedback :)

**Comment by ja-pa** [comment]
Thanks
