### ISSUE TITLE
Support metrics output in prometheus format

### ISSUE THREAD

**Issue by KVInventoR** [dmachard/dnstap-receiver#10]
Dnstap-receiver already have a build-in web server,
it will be cool from build-in functionality return metrics in prometheus format.

**Comment by dmachard** [comment]
I planned to do that. Your proposal is welcome

**Comment by dmachard** [comment]
feature implemented in commit https://github.com/dmachard/dnstap-receiver/commit/9194bbe9f040536e3f2eeec7205c3541f14e6155
