### ISSUE TITLE
command line argument not overlapped config settings

### ISSUE THREAD

**Issue by KVInventoR** [dmachard/dnstap-receiver#11]
I found a small issue, I use a command:

/usr/bin/python3 -u /usr/local/bin/dnstap_receiver -c dnstap-local.conf -p 8000
but when I checked:
netstat -anp|grep 6000
tcp        0      0 0.0.0.0:6000            0.0.0.0:*               LISTEN      29696/python3

looks like dnstap_receiver ignored additional arguments for port usage and just use default settings from configuration file.

**Comment by dmachard** [comment]
fix in release 3.0.0
