### ISSUE TITLE
Make output for country in geoip module configurable over settings

### ISSUE THREAD

**Issue by KVInventoR** [dmachard/dnstap-receiver#13]
By default output country is: 

response.country.name

but grafana panel:  https://grafana.com/grafana/plugins/grafana-worldmap-panel
required to have:
Countries (2 letter codes)
Countries (3 letter codes)

I would like to have a possibility to change default settings from name to iso_code over dnstap_settings

**Comment by dmachard** [comment]
implemented in release 3.0.0
