### ISSUE TITLE
Only one output is working at a time

### ISSUE THREAD

**Issue by ExaneServerTeam** [dmachard/dnstap-receiver#18]
Hello,

First of all. Thanks for this great piece of code !

Running some tests I noticed that only one output could be enable at a time.
Source of the issue is that there is a single queue for N consumers, so it is not possible to have a Y type of ouput.

I had a look at the following that could help setting up a specific queue per consumer.
https://github.com/smithk86/asyncio-multisubscriber-queue

-> This lib is python >= 3.7 only. Not an option for me (Running RHEL8 with python3.6) ...

Frédéric

**Comment by dmachard** [comment]
I planned to add the support of multiple queue for the next release but I need to check the impact regarding the performance.
---
Effectivement aujourd'hui c'est limité,  j'avais prévu cette amélioration avec simplement une liste de "queue".
une file pour chaque consommateur/output qui serait remplit par le récepteur quand un message dnstap est reçu.

**Comment by ExaneServerTeam** [comment]
@dmachard Thanks for your quick feedback. This is a good news you have it in mind, I'll wait & see then ..
Good luck with that and thanks for merging my PRs ;)

**Comment by dmachard** [comment]
implemented in the commit https://github.com/dmachard/dnstap-receiver/commit/7abbcd19bb4506f3e40fb11c00d552d35e817c2e

more tests are needed and any feedbacks regarding the performance will be appreciate.

**Comment by ExaneServerTeam** [comment]
Hello,

I had a quick run. Looks very good to me. Indeed the Y setup is now working (File ouput + remote TCP)

The next graph shows last release (2.2.1) vs current git master: busy user goes from 9% vs 2,4% !

The traffic Hole (on the network part) is me switching from release to git master

![image](https://user-images.githubusercontent.com/29705363/102212653-d5bfb900-3ed5-11eb-9a4e-b5ae31322f48.png)

**Comment by dmachard** [comment]
implemented in release 3.0.0
