### ISSUE TITLE
Syslog output: Object of type 'bytes' is not JSON serializable

### ISSUE THREAD

**Issue by ajoergensen** [dmachard/dnstap-receiver#21]
Hi,

I'm using dnstap_receiver with dnsdist and sending to syslog in text format works fine - but if I switch the output type to json, it throws this trace: 

```
Jan 11 17:35:24 server dnstap_receiver[20869]: Task exception was never retrieved
Jan 11 17:35:24 server dnstap_receiver[20869]: future: <Task finished coro=<handle() done, defined at /opt/dnstap/lib/python3.6/site-packages/dnstap_receiver/outputs/output_syslog.py:52> exception=TypeError("Object of type 'bytes' is
Jan 11 17:35:24 server dnstap_receiver[20869]: Traceback (most recent call last):
Jan 11 17:35:24 server dnstap_receiver[20869]:   File "/opt/dnstap/lib/python3.6/site-packages/dnstap_receiver/outputs/output_syslog.py", line 62, in handle
Jan 11 17:35:24 server dnstap_receiver[20869]:     await syslog_tcpclient(output_cfg, queue)
Jan 11 17:35:24 server dnstap_receiver[20869]:   File "/opt/dnstap/lib/python3.6/site-packages/dnstap_receiver/outputs/output_syslog.py", line 36, in syslog_tcpclient
Jan 11 17:35:24 server dnstap_receiver[20869]:     msg = transform.convert_dnstap(fmt=output_cfg["format"], tapmsg=tapmsg)
Jan 11 17:35:24 server dnstap_receiver[20869]:   File "/opt/dnstap/lib/python3.6/site-packages/dnstap_receiver/outputs/transform.py", line 35, in convert_dnstap
Jan 11 17:35:24 server dnstap_receiver[20869]:     msg = json.dumps(tapmsg)
Jan 11 17:35:24 server dnstap_receiver[20869]:   File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
Jan 11 17:35:24 server dnstap_receiver[20869]:     return _default_encoder.encode(obj)
Jan 11 17:35:24 server dnstap_receiver[20869]:   File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
Jan 11 17:35:24 server dnstap_receiver[20869]:     chunks = self.iterencode(o, _one_shot=True)
Jan 11 17:35:24 server dnstap_receiver[20869]:   File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
Jan 11 17:35:24 server dnstap_receiver[20869]:     return _iterencode(o, 0)
Jan 11 17:35:24 server dnstap_receiver[20869]:   File "/usr/lib/python3.6/json/encoder.py", line 180, in default
Jan 11 17:35:24 server dnstap_receiver[20869]:     o.__class__.__name__)
Jan 11 17:35:24 server dnstap_receiver[20869]: TypeError: Object of type 'bytes' is not JSON serializable
```
dnsdist version is 1.5.1 \
dnstap_receiver version is latest available via pip.

Let me know if I can provide more data.

tia,
Allan

**Comment by KVInventoR** [comment]
Hi @dmachard 

Same for me,  I have stdout in json format with GeoIP enabled

`Task exception was never retrieved
future: <Task finished name='Task-2' coro=<handle() done, defined at /home/dnstap/dnstap_receiver/outputs/output_stdout.py:27> exception=TypeError('Object of type bytes is not JSON serializable')>
Traceback (most recent call last):
  File "/home/dnstap/dnstap_receiver/outputs/output_stdout.py", line 38, in handle
    msg = transform.convert_dnstap(fmt=output_cfg["format"], tapmsg=tapmsg)
  File "/home/dnstap/dnstap_receiver/outputs/transform.py", line 35, in convert_dnstap
    msg = json.dumps(tapmsg)
  File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable`

**Comment by dmachard** [comment]
fix in commit https://github.com/dmachard/dnstap-receiver/commit/4080d630b173169e985f6566c61b30aa6e8200b3
the fix will be released in next release

**Comment by dmachard** [comment]
version 4.2 released
