### ISSUE TITLE
Rename all metrics which has sum of another metrics

### ISSUE THREAD

**Issue by KVInventoR** [dmachard/dnstap-receiver#22]
Hi,

I would like to ask you about feature request.
If if will run next query:
`url -s --user admin:changeme http://localhost:8080/metrics|grep qps
# HELP dnstap_qps Number of queries per second received
# TYPE dnstap_qps gauge
dnstap_qps 701
# HELP dnstap_qps Number of queries per second for this dnstap identity
# TYPE dnstap_qps gauge
dnstap_qps{identity="alpha-vm01"} 272
# HELP dnstap_qps Number of queries per second for this dnstap identity
# TYPE dnstap_qps gauge
dnstap_qps{identity="dns-cache01"} 369
# HELP dnstap_qps Number of queries per second for this dnstap identity
# TYPE dnstap_qps gauge
dnstap_qps{identity="dns-cache02"} 60`

Here we will have metrics per monitored DNS server and one metrics: dnstap_qps, I would like to add prefix _total to the end of all metrics which contains sum from another metrics, like this:

dnstap_qps_total
dnstap_qps{identity="alpha-vm01"} 
dnstap_qps{identity="dns-cache01"} 
dnstap_qps{identity="dns-cache02"} 

Reason:
It's difficult to build dynamic grafana dashboard, because need to control if metric has identity or not.

Also, if we will have: dnstap_*_total it will be useful to have possibility to add a custom labels over dnstap configuration.

**Comment by dmachard** [comment]
This FR is implemented in the commit https://github.com/dmachard/dnstap-receiver/commit/610d0e844c0676127484702d835c319e3fc1bc27, it will be released on next release.
