### ISSUE TITLE
Feature Request:  Execute external code on log rotation

### ISSUE THREAD

**Issue by variverrat** [dmachard/dnstap-receiver#23]
Similar to the -z switch on tcpdump, pass in the name of the newly rotated log file to an external script to take action.  

In tcpdump, it is usually used to compress and transfer for archiving via execution of an external script.

**Comment by dmachard** [comment]
Feature implemented on the first stable release of the new tool [dns-collector](https://github.com/dmachard/go-dnscollector). Please to take a look.
