### ISSUE TITLE
TCP-Socket-Connection with dnsdist shows no output

### ISSUE THREAD

**Issue by tomarcade** [dmachard/dnstap-receiver#24]
Hi
Using the latest dnstap_receiver (4.2.0). I've configured dnsdist like this:

```
remotelogger = newRemoteLogger("127.0.0.1:6000")
addResponseAction(AllRule(), RemoteLogResponseAction(remotelogger))
addAction(AllRule(), RemoteLogAction(remotelogger)
```
The dnsdist_reciver-startup looks like this:
```
2021-03-03 10:20:42,685 DEBUG External config file loaded
2021-03-03 10:20:42,685 DEBUG Start receiver...
2021-03-03 10:20:42,685 DEBUG Output handler: stdout
2021-03-03 10:20:42,685 DEBUG Input handler: tcp socket
2021-03-03 10:20:42,686 DEBUG Input handler: listening on 0.0.0.0:6000
2021-03-03 10:20:42,687 DEBUG Webserver: listening on 0.0.0.0:8080
```

Looking at the traffic with tcpdump, I see, that dnsdist is sending the request/response to the remotelogger-socket (127.0.0.1:6000):
```
$ tcpdump -i lo -s0 -nn port 6000 -A
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on lo, link-type EN10MB (Ethernet), capture size 262144 bytes
10:21:29.872725 IP 127.0.0.1.49440 > 127.0.0.1.6000: Flags [P.], seq 4059372952:4059373167, ack 4131425596, win 342, length 215
E...8.@.@............ .p.....@.<P..V.....[....&.!..ZM..y..Y... .(.2.....:.
`..@3H.....P..9X...b.
.google.com.....j
(.....0..9.......5.x....&.!..ZM..y..Y... .(.2.....:.
`..@_H.....P.aX...b.
.google.com.....j(....
.google.com..... ..*.....(.....0..9.......5
10:21:29.872786 IP 127.0.0.1.6000 > 127.0.0.1.49440: Flags [R], seq 4131425596, win 0, length 0
E..(..@.@.!..........p. .@.<....P...U...
```

But on the dnstap_receiver, I don't get any output to stdout. I also tried with sending to syslog.., but also no output on the syslog-server.
Any hints for this? Using unix-socket as an dnsdist-endpoint works perfect.

Many thanks.
Kind regards,
Tom 

BTW: When using dnstap-receiver with unix-socket: is there a way to include the destination port (server-side) in the output? Because we're establishing DoT/DoH and we currently cannot see, if the traffic is coming in with with TCP-443 (DoH) or with TCP-853 (DoT) or with normal DNS.

**Comment by dmachard** [comment]
Hi,

Your dnsdist configuration is wrong, the _RemoteLogger_ is not compatible with the dnstap receiver
You need to activate the _FrameStreamTcpLogger_ feature like described [here ](https://github.com/dmachard/dnstap-receiver#dnsdist) or use the [pdns-protobuf-receiver ](https://github.com/PowerDNS/pdns-protobuf-receiver)

denis

**Comment by tomarcade** [comment]
Hi Denis
Thanks for your hint, works now.
