### ISSUE TITLE
CPU utilisation per container

### ISSUE THREAD

**Issue by KVInventoR** [dmachard/dnstap-receiver#28]
Hi there,

I have a poor CPU utilization, DNSTap-receiver unforthenatly uses only 1 CPU core for all workloads.

```
Average:     CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
Average:     all   18.55    0.00    1.71    0.00    0.00    0.13    0.00    0.00    0.00   79.61
Average:       0   99.00    0.00    1.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00
Average:       1    2.67    0.00    1.67    0.00    0.00    1.00    0.00    0.00    0.00   94.67
Average:       2    4.01    0.00    1.34    0.00    0.00    0.00    0.00    0.00    0.00   94.65
Average:       3    3.02    0.00    2.35    0.00    0.00    0.00    0.00    0.00    0.00   94.63
Average:       4    4.03    0.00    1.34    0.00    0.00    0.00    0.00    0.00    0.00   94.63
Average:       5    5.02    0.00    2.34    0.00    0.00    0.00    0.00    0.00    0.00   92.64
Average:       6    5.02    0.00    2.01    0.00    0.00    0.00    0.00    0.00    0.00   92.98
Average:       7   25.33    0.00    1.67    0.00    0.00    0.00    0.00    0.00    0.00   73.00
```

```
dnstap_pps 4485
dnstap_qps 4397
dnstap_rps 88
dnstap_domains 243431
dnstap_clients 822
dnstap_queries 71717861
```

Is it possible to implement multiprocessing for dnstap_receiver and switcher in conf file between multithreads and multi process?

Also, I did experiment and started more dnstap-receiver containers with nginx as TCP load balancer in front, but didn't got performance improve

**Comment by dmachard** [comment]
Perhaps some improvements could be done with [ProcessPoolExecutor](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ProcessPoolExecutor )

Can you specific the number of dnstap sender in your case ? and if one or severals outputs are configured ?

**Comment by dmachard** [comment]
The first stable release of the new [dns-collector i](https://github.com/dmachard/go-dnscollector)s available So far the performance are great. Prefer to use this tool if you want better performance.

**Comment by KVInventoR** [comment]
@dmachard  
after some investigation, I found that performance was degraded when I used geoip enabled


I will try new solution, thank you

**Comment by dmachard** [comment]
Ok, thanks ,
your feedback will be appreciated with the new solution
