### ISSUE TITLE
FrameStreamLogger: family 2 not supported

### ISSUE THREAD

**Issue by hk-awil** [dmachard/dnstap-receiver#4]
Hello Denis

I tried the dnstap-receiver v1.3.0 with pip install in a python 3.6.8 venv together with pdns_recursor Version 4.4.0. and 4.3.5.
And I tried also your docker image together with pdns_recursor Version 4.4.0. and 4.3.5.
Regardless of the pdns_recursor version and dnstap-receiver installation I see the following messages in pdns_recursor log:
```
Nov 04 11:23:55 pdns_rec1 pdns_recursor[59056]: Error while starting dnstap framestream logger to '192.168.0.3:6000: FrameStreamLogger: family 2 not supported
Nov 04 11:23:55 pdns_rec1 pdns_recursor[59056]: Error while starting dnstap framestream logger to '192.168.0.3:6000: FrameStreamLogger: family 2 not supported
Nov 04 11:23:55 pdns_rec1 pdns_recursor[59056]: Error while starting dnstap framestream logger to '192.168.0.3:6000: FrameStreamLogger: family 2 not supported
```
Do you have an idea, what's the root cause of the problem? 
Is this a pdns_recursor or a dnstap-receiver problem?

Best regards
Daniel

**Comment by dmachard** [comment]
Hello,

I think the problem is on your pdns_recursor and the version of the  **fstrm** library according to the thread  [here ](https://mailman.powerdns.com/pipermail/pdns-users/2020-June/026725.html)

> The problem is your version of the fstrm lib only supports unix domain sockets. inet and inet6 support are recent addtions to libfstrm. 

Denis

**Comment by hk-awil** [comment]
Hello Denis,

Thank you for the hint.

Daniel
