### ISSUE TITLE
Issue during start, KeyError: 'syslog'`

### ISSUE THREAD

**Issue by KVInventoR** [dmachard/dnstap-receiver#6]
/etc/dnstap-receiver/dnstap.conf

output:
  stdout:
    # enable or disable
    enable: true
    # format available text|json|yaml
    format: text

Issue:
root@dns-balance:~# ./miniconda3/bin/dnstap_receiver -l 127.0.0.1 -p 8000 -v -c /etc/dnstap-receiver/dnstap.conf
2020-11-11 11:53:17,798 Start receiver...
2020-11-11 11:53:17,798 Using selector: EpollSelector
Traceback (most recent call last):
  File "./miniconda3/bin/dnstap_receiver", line 8, in <module>
    sys.exit(start_receiver())
  File "/root/miniconda3/lib/python3.8/site-packages/dnstap_receiver/receiver.py", line 302, in start_receiver
    if cfg["output"]["syslog"]["enable"]:
KeyError: 'syslog'

it's mistake to check dict which doesn't have a key: syslog

**Comment by dmachard** [comment]
In fact this error should not happened because a default config file (with all keys) is loaded before the external one.
Can you check if you have a dnstap.conf file in the folder /root/miniconda3/lib/python3.8/site-packages/dnstap_receiver/  and the content of this file ?

**Comment by dmachard** [comment]
I will check what happening, in the meantime, copy a complete config file located here /root/miniconda3/lib/python3.8/site-packages/dnstap_receiver/dnstap.conf to /etc/dnstap-receiver/dnstap.conf

**Comment by dmachard** [comment]
issue fixed in release 2.0.2
