### ISSUE TITLE
Extend dnstap-receiver by geoip

### ISSUE THREAD

**Issue by KVInventoR** [dmachard/dnstap-receiver#7]
I am working on some a little integration and for me it looks really cool, if dnstap-receiver will have an integration with geoip, it will give possibility to make more useful statistics on the fly.

**Comment by dmachard** [comment]
support added commit https://github.com/dmachard/dnstap-receiver/commit/546fb5e8c792074e593e544b9e7f8e5146805dda
doc : https://github.com/dmachard/dnstap-receiver#geoip-support

but feature not tested in real condition

**Comment by KVInventoR** [comment]
looks imagine
thank you
